### ISSUE TITLE
ARS Search Engine - Save query

### ISSUE THREAD

**Issue by mvb-nt** [NHMDenmark/DaSSCo-asset-service#77] opened 2024-06-10 10:52 UTC
DUPLICATE. TO BE DELETED. (Can't figure out how?)

**Comment by Grand666** [comment] 2024-06-14 09:16
Duplicate of https://github.com/orgs/NHMDenmark/projects/32/views/1?pane=issue&itemId=66777736

**Closed by Grand666** 2024-06-14 09:16 UTC
Labels: Refinement, WK5A
